"""CMake file generator visitor module."""

__author__ = 'sgu'

# util
from typing import Dict, Tuple

# jinja2
from jinja2 import Environment, FileSystemLoader

# user relative imports
from ..gen.python.TestSuite.TestSuiteParser import TestSuiteParser
from ..symboltable.symbol_table import SymbolTable
from ..gen.python.TestSuite.TestSuiteVisitor import TestSuiteVisitor
from ..utils.suggest_variables import get_scope


class CMakeFileGeneratorVisitor(TestSuiteVisitor):
    symbol_table: SymbolTable
    work_path: str

    def __init__(self, template_path: str = 'tdd-dsl/tddlspserver/filewriter/jinjatemplates/cmake', files: Dict[str, Tuple[float, str, str]] = {}, symbol_table: SymbolTable = None, work_path: str = 'tdd-dsl/output'):
        """
        Generate CMake files for test case

        :param template_path: system path to jinja templates
        :param files: File attributes of files generated by the tdd-dsl server
        :param symbol_table: Symbol table to resolve symbols of tdd-dsl server
        :param work_path: system path to generate test suite
        """
        super().__init__()

        self.files: dict[str, Tuple[float, str, str]] = files

        self.symbol_table = symbol_table

        self.template_path = template_path

        # Load Jinja2 templates
        self.environment = Environment(loader=FileSystemLoader(template_path))

        self.work_path = work_path

    # Visit a parse tree produced by TestSuiteParser#test_case.
    def visitTest_case(self, ctx: TestSuiteParser.Test_caseContext) -> dict[str, Tuple[float, str, str]]:
        # Update test case symbol
        test_case_symbol = get_scope(ctx, self.symbol_table)
        pass