name: Upload cp-dsl Package

on:
  pull_request:
    paths: 
        - 'cp-dsl/**'
    

permissions:
  contents: read

jobs:
  deploy_on_pypi:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    -- name: "Installs dependencies"
      shell: bash
      run: |
          cd cp-dsl/
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
    - name: "Builds and uploads to PyPI"
      shell: bash
      env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
      run: |
             cd cp-dsl/
             python3 setup.py sdist bdist_wheel
             python3 -m twine upload -u "$TWINE_USERNAME" -p "TWINE_PASSWORD" dist/*
        
